In [2]:
import pandas as pd

ModuleNotFoundError: No module named 'pandas'

In [ ]:
data = pd.read_csv('loan_approval_dataset.csv')

In [ ]:
data.drop(columns = ['loan_id'], inplace=True)

NameError: name 'data' is not defined

In [ ]:
data.columns

NameError: name 'data' is not defined

In [ ]:
data.columns = data.columns.str.strip()

NameError: name 'data' is not defined

In [ ]:
data.columns

Index(['no_of_dependents', 'education', 'self_employed', 'income_annum',
       'loan_amount', 'loan_term', 'cibil_score', 'residential_assets_value',
       'commercial_assets_value', 'luxury_assets_value', 'bank_asset_value',
       'loan_status'],
      dtype='object')

In [ ]:
data

NameError: name 'data' is not defined

In [ ]:
data.columns

Index(['no_of_dependents', 'education', 'self_employed', 'income_annum',
       'loan_amount', 'loan_term', 'cibil_score', 'residential_assets_value',
       'commercial_assets_value', 'luxury_assets_value', 'bank_asset_value',
       'loan_status'],
      dtype='object')

In [ ]:
data['Assets'] = data.residential_assets_value + data.commercial_assets_value+data.luxury_assets_value + data.bank_asset_value

:

In [ ]:
data.drop(columns = ['residential_assets_value','commercial_assets_value','luxury_assets_value','bank_asset_value'], inplace = True)

In [ ]:
data

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,loan_status,Assets
0,2,Graduate,No,9600000,29900000,12,778,Approved,50700000
1,0,Not Graduate,Yes,4100000,12200000,8,417,Rejected,17000000
2,3,Graduate,No,9100000,29700000,20,506,Rejected,57700000
3,3,Graduate,No,8200000,30700000,8,467,Rejected,52700000
4,5,Not Graduate,Yes,9800000,24200000,20,382,Rejected,55000000
...,...,...,...,...,...,...,...,...,...
4264,5,Graduate,Yes,1000000,2300000,12,317,Rejected,7400000
4265,0,Not Graduate,Yes,3300000,11300000,20,559,Approved,20000000
4266,2,Not Graduate,No,6500000,23900000,18,457,Rejected,39000000
4267,1,Not Graduate,No,4100000,12800000,8,780,Approved,28800000
4268,1,Graduate,No,9200000,29700000,10,607,Approved,77300000

In [ ]:
data.isnull().sum()

no_of_dependents    0
education           0
self_employed       0
income_annum        0
loan_amount         0
loan_term           0
cibil_score         0
loan_status         0
Assets              0
dtype: int64

In [ ]:
data

NameError: name 'data' is not defined

In [ ]:
data.education.unique()

array([' Graduate', ' Not Graduate'], dtype=object)

In [ ]:
def clean_data(st):
    st = st.strip()
    return st

In [ ]:
clean_data(' Graduate')

'Graduate'

In [ ]:
data.education = data.education.apply(clean_data)

In [ ]:
data.education.unique()

array(['Graduate', 'Not Graduate'], dtype=object)

In [ ]:
data['education'] = data['education'].replace(['Graduate', 'Not Graduate'],[1,0])

In [ ]:
data

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,loan_status,Assets
0,2,1,No,9600000,29900000,12,778,Approved,50700000
1,0,0,Yes,4100000,12200000,8,417,Rejected,17000000
2,3,1,No,9100000,29700000,20,506,Rejected,57700000
3,3,1,No,8200000,30700000,8,467,Rejected,52700000
4,5,0,Yes,9800000,24200000,20,382,Rejected,55000000
...,...,...,...,...,...,...,...,...,...
4264,5,1,Yes,1000000,2300000,12,317,Rejected,7400000
4265,0,0,Yes,3300000,11300000,20,559,Approved,20000000
4266,2,0,No,6500000,23900000,18,457,Rejected,39000000
4267,1,0,No,4100000,12800000,8,780,Approved,28800000
4268,1,1,No,9200000,29700000,10,607,Approved,77300000

In [ ]:
data.self_employed.unique()

array([' No', ' Yes'], dtype=object)

In [ ]:
data.self_employed = data.self_employed.apply(clean_data)

In [ ]:
data.self_employed.unique()

array(['No', 'Yes'], dtype=object)

In [ ]:
data.self_employed = data.self_employed.replace(['No', 'Yes'],[0,1])

In [ ]:
data

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,loan_status,Assets
0,2,1,0,9600000,29900000,12,778,Approved,50700000
1,0,0,1,4100000,12200000,8,417,Rejected,17000000
2,3,1,0,9100000,29700000,20,506,Rejected,57700000
3,3,1,0,8200000,30700000,8,467,Rejected,52700000
4,5,0,1,9800000,24200000,20,382,Rejected,55000000
...,...,...,...,...,...,...,...,...,...
4264,5,1,1,1000000,2300000,12,317,Rejected,7400000
4265,0,0,1,3300000,11300000,20,559,Approved,20000000
4266,2,0,0,6500000,23900000,18,457,Rejected,39000000
4267,1,0,0,4100000,12800000,8,780,Approved,28800000
4268,1,1,0,9200000,29700000,10,607,Approved,77300000

In [ ]:
data.loan_status.unique()

array([' Approved', ' Rejected'], dtype=object)

In [ ]:
data.loan_status = data.loan_status.apply(clean_data)

In [4]:
data.loan_status.unique()

NameError: name 'data' is not defined

In [ ]:
data.loan_status = data.loan_status.replace(['Approved', 'Rejected'],[1,0])

In [ ]:
data

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,loan_status,Assets
0,2,1,0,9600000,29900000,12,778,1,50700000
1,0,0,1,4100000,12200000,8,417,0,17000000
2,3,1,0,9100000,29700000,20,506,0,57700000
3,3,1,0,8200000,30700000,8,467,0,52700000
4,5,0,1,9800000,24200000,20,382,0,55000000
...,...,...,...,...,...,...,...,...,...
4264,5,1,1,1000000,2300000,12,317,0,7400000
4265,0,0,1,3300000,11300000,20,559,1,20000000
4266,2,0,0,6500000,23900000,18,457,0,39000000
4267,1,0,0,4100000,12800000,8,780,1,28800000
4268,1,1,0,9200000,29700000,10,607,1,77300000

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
input_data = data.drop(columns=['loan_status'])
output_data = data['loan_status']

In [ ]:
input_data

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,Assets
0,2,1,0,9600000,29900000,12,778,50700000
1,0,0,1,4100000,12200000,8,417,17000000
2,3,1,0,9100000,29700000,20,506,57700000
3,3,1,0,8200000,30700000,8,467,52700000
4,5,0,1,9800000,24200000,20,382,55000000
...,...,...,...,...,...,...,...,...
4264,5,1,1,1000000,2300000,12,317,7400000
4265,0,0,1,3300000,11300000,20,559,20000000
4266,2,0,0,6500000,23900000,18,457,39000000
4267,1,0,0,4100000,12800000,8,780,28800000
4268,1,1,0,9200000,29700000,10,607,77300000

In [ ]:
output_data

0       1
1       0
2       0
3       0
4       0
       ..
4264    0
4265    1
4266    0
4267    1
4268    1
Name: loan_status, Length: 4269, dtype: int64

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(input_data,output_data, test_size=0.2)

In [ ]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((3415, 8), (854, 8), (3415,), (854,))

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler = StandardScaler()

In [ ]:
x_train_scaled = scaler.fit_transform(x_train)

In [ ]:
x_test_scaled = scaler.transform(x_test)

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
model = LogisticRegression()

In [ ]:
model.fit(x_train_scaled, y_train)

NameError: name 'model' is not defined

In [ ]:
model.score(x_test_scaled, y_test)

0.9098360655737705

In [ ]:
pred_data = pd.DataFrame([['2','1','0','9600000','29900000','12','778','50700000']],columns=['no_of_dependents','education','self_employed','income_annum','loan_amount','loan_term','cibil_score','Assets'])

In [ ]:
pred_data = scaler.transform(pred_data)

In [ ]:
model.predict(pred_data)

array([1], dtype=int64)

In [ ]:
import pickle as pk

In [ ]:
pk.dump(model, open('model.pkl','wb'))

In [ ]:
pk.dump(scaler,open('scaler.pkl','wb'))